<!doctype html>
<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="/assets/css/style.css">
    <link rel="stylesheet" href="/assets/css/bootstrap.min.css">

    <title>MustaPower Framework!</title>
</head>
<body>
<div class="container">
    <h1>Página não encontrada!</h1>
    <p>Por favor, verifique se a URL digitada está correta.</p>
    <p><a href="javascript:history.back()" class="btn btn-default">Voltar</a></p>
</div>
<script src="/assets/js/bootstrap.min.js"></script>
<script src="/assets/js/jquery.min.js"></script>
</body>
</html>